name: Build and Push Docker images

on:
  push:
    branches:
      - master
    paths:
      - 'version.txt'
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Read Version
      id: version
      run: echo "::set-output name=VERSION::$(cat version.txt)"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          nabilch900/obscreen:v${{ steps.version.outputs.VERSION }}
          nabilch900/obscreen:latest
        platforms: linux/amd64, linux/arm64/v8, linux/arm/v7

    - name: Create and push manifest
      uses: docker/metadata-action@v3
      with:
        images: nabilch900/obscreen
        tags: type=semver,pattern=v{{version}}
        flavor: |
          latest=true
